###### Class com.app.hider.master.pro.R is created by jadx
###### Class com.app.hider.master.pro.R.anim is created by jadx
###### Class com.app.hider.master.pro.R.animator is created by jadx
###### Class com.app.hider.master.pro.R.array is created by jadx
###### Class com.app.hider.master.pro.R.attr is created by jadx
###### Class com.app.hider.master.pro.R.bool is created by jadx
###### Class com.app.hider.master.pro.R.color is created by jadx
###### Class com.app.hider.master.pro.R.dimen is created by jadx
###### Class com.app.hider.master.pro.R.drawable is created by jadx
###### Class com.app.hider.master.pro.R.id is created by jadx
###### Class com.app.hider.master.pro.R.integer is created by jadx
###### Class com.app.hider.master.pro.R.interpolator is created by jadx
###### Class com.app.hider.master.pro.R.layout is created by jadx
###### Class com.app.hider.master.pro.R.menu is created by jadx
###### Class com.app.hider.master.pro.R.mipmap is created by jadx
###### Class com.app.hider.master.pro.R.raw is created by jadx
###### Class com.app.hider.master.pro.R.string is created by jadx
###### Class com.app.hider.master.pro.R.style is created by jadx
###### Class com.app.hider.master.pro.R.transition is created by jadx
###### Class com.app.hider.master.pro.R.xml is created by jadx