package com.amazonaws.regions;

import com.amazonaws.services.s3.internal.Constants;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;

/* JADX INFO: loaded from: classes.dex */
class RegionDefaults {
    RegionDefaults() {
    }

    public static List<Region> a() {
        ArrayList arrayList = new ArrayList();
        Region region = new Region("ap-northeast-1", "amazonaws.com");
        arrayList.add(region);
        a(region, ServiceAbbreviations.p, "autoscaling.ap-northeast-1.amazonaws.com", false, true);
        a(region, "cognito-identity", "cognito-identity.ap-northeast-1.amazonaws.com", false, true);
        a(region, "cognito-idp", "cognito-idp.ap-northeast-1.amazonaws.com", false, true);
        a(region, "cognito-sync", "cognito-sync.ap-northeast-1.amazonaws.com", false, true);
        a(region, "data.iot", "data.iot.ap-northeast-1.amazonaws.com", false, true);
        a(region, ServiceAbbreviations.e, "dynamodb.ap-northeast-1.amazonaws.com", false, true);
        a(region, ServiceAbbreviations.f, "ec2.ap-northeast-1.amazonaws.com", false, true);
        a(region, ServiceAbbreviations.v, "elasticloadbalancing.ap-northeast-1.amazonaws.com", false, true);
        a(region, "firehose", "firehose.ap-northeast-1.amazonaws.com", false, true);
        a(region, "iot", "iot.ap-northeast-1.amazonaws.com", false, true);
        a(region, "kinesis", "kinesis.ap-northeast-1.amazonaws.com", false, true);
        a(region, "kms", "kms.ap-northeast-1.amazonaws.com", false, true);
        a(region, "lambda", "lambda.ap-northeast-1.amazonaws.com", false, true);
        a(region, "logs", "logs.ap-northeast-1.amazonaws.com", false, true);
        a(region, "polly", "polly.ap-northeast-1.amazonaws.com", false, true);
        a(region, "s3", "s3.ap-northeast-1.amazonaws.com", false, true);
        a(region, ServiceAbbreviations.l, "sdb.ap-northeast-1.amazonaws.com", false, true);
        a(region, ServiceAbbreviations.m, "sns.ap-northeast-1.amazonaws.com", false, true);
        a(region, ServiceAbbreviations.n, "sqs.ap-northeast-1.amazonaws.com", false, true);
        a(region, ServiceAbbreviations.t, "sts.amazonaws.com", false, true);
        Region region2 = new Region("ap-northeast-2", "amazonaws.com");
        arrayList.add(region2);
        a(region2, ServiceAbbreviations.p, "autoscaling.ap-northeast-2.amazonaws.com", false, true);
        a(region2, "cognito-identity", "cognito-identity.ap-northeast-2.amazonaws.com", false, true);
        a(region2, "cognito-idp", "cognito-idp.ap-northeast-2.amazonaws.com", false, true);
        a(region2, "cognito-sync", "cognito-sync.ap-northeast-2.amazonaws.com", false, true);
        a(region2, "data.iot", "data.iot.ap-northeast-2.amazonaws.com", false, true);
        a(region2, ServiceAbbreviations.e, "dynamodb.ap-northeast-2.amazonaws.com", false, true);
        a(region2, ServiceAbbreviations.f, "ec2.ap-northeast-2.amazonaws.com", false, true);
        a(region2, ServiceAbbreviations.v, "elasticloadbalancing.ap-northeast-2.amazonaws.com", false, true);
        a(region2, "iot", "iot.ap-northeast-2.amazonaws.com", false, true);
        a(region2, "kinesis", "kinesis.ap-northeast-2.amazonaws.com", false, true);
        a(region2, "kms", "kms.ap-northeast-2.amazonaws.com", false, true);
        a(region2, "lambda", "lambda.ap-northeast-2.amazonaws.com", false, true);
        a(region2, "logs", "logs.ap-northeast-2.amazonaws.com", false, true);
        a(region2, "polly", "polly.ap-northeast-2.amazonaws.com", false, true);
        a(region2, "s3", "s3.ap-northeast-2.amazonaws.com", false, true);
        a(region2, ServiceAbbreviations.m, "sns.ap-northeast-2.amazonaws.com", false, true);
        a(region2, ServiceAbbreviations.n, "sqs.ap-northeast-2.amazonaws.com", false, true);
        a(region2, ServiceAbbreviations.t, "sts.ap-northeast-2.amazonaws.com", false, true);
        Region region3 = new Region("ap-south-1", "amazonaws.com");
        arrayList.add(region3);
        a(region3, ServiceAbbreviations.p, "autoscaling.ap-south-1.amazonaws.com", false, true);
        a(region3, "cognito-identity", "cognito-identity.ap-south-1.amazonaws.com", false, true);
        a(region3, "cognito-idp", "cognito-idp.ap-south-1.amazonaws.com", false, true);
        a(region3, "cognito-sync", "cognito-sync.ap-south-1.amazonaws.com", false, true);
        a(region3, ServiceAbbreviations.e, "dynamodb.ap-south-1.amazonaws.com", false, true);
        a(region3, ServiceAbbreviations.f, "ec2.ap-south-1.amazonaws.com", false, true);
        a(region3, ServiceAbbreviations.v, "elasticloadbalancing.ap-south-1.amazonaws.com", false, true);
        a(region3, "kinesis", "kinesis.ap-south-1.amazonaws.com", false, true);
        a(region3, "kms", "kms.ap-south-1.amazonaws.com", false, true);
        a(region3, "lambda", "lambda.ap-south-1.amazonaws.com", false, true);
        a(region3, "logs", "logs.ap-south-1.amazonaws.com", false, true);
        a(region3, "polly", "polly.ap-south-1.amazonaws.com", false, true);
        a(region3, "s3", "s3.ap-south-1.amazonaws.com", false, true);
        a(region3, ServiceAbbreviations.m, "sns.ap-south-1.amazonaws.com", false, true);
        a(region3, ServiceAbbreviations.n, "sqs.ap-south-1.amazonaws.com", false, true);
        a(region3, ServiceAbbreviations.t, "sts.amazonaws.com", false, true);
        Region region4 = new Region("ap-southeast-1", "amazonaws.com");
        arrayList.add(region4);
        a(region4, ServiceAbbreviations.p, "autoscaling.ap-southeast-1.amazonaws.com", false, true);
        a(region4, "cognito-identity", "cognito-identity.ap-southeast-1.amazonaws.com", false, true);
        a(region4, "cognito-idp", "cognito-idp.ap-southeast-1.amazonaws.com", false, true);
        a(region4, "cognito-sync", "cognito-sync.ap-southeast-1.amazonaws.com", false, true);
        a(region4, "data.iot", "data.iot.ap-southeast-1.amazonaws.com", false, true);
        a(region4, ServiceAbbreviations.e, "dynamodb.ap-southeast-1.amazonaws.com", false, true);
        a(region4, ServiceAbbreviations.f, "ec2.ap-southeast-1.amazonaws.com", false, true);
        a(region4, ServiceAbbreviations.v, "elasticloadbalancing.ap-southeast-1.amazonaws.com", false, true);
        a(region4, "iot", "iot.ap-southeast-1.amazonaws.com", false, true);
        a(region4, "kinesis", "kinesis.ap-southeast-1.amazonaws.com", false, true);
        a(region4, "kms", "kms.ap-southeast-1.amazonaws.com", false, true);
        a(region4, "lambda", "lambda.ap-southeast-1.amazonaws.com", false, true);
        a(region4, "logs", "logs.ap-southeast-1.amazonaws.com", false, true);
        a(region4, "polly", "polly.ap-southeast-1.amazonaws.com", false, true);
        a(region4, "s3", "s3.ap-southeast-1.amazonaws.com", false, true);
        a(region4, ServiceAbbreviations.l, "sdb.ap-southeast-1.amazonaws.com", false, true);
        a(region4, ServiceAbbreviations.m, "sns.ap-southeast-1.amazonaws.com", false, true);
        a(region4, ServiceAbbreviations.n, "sqs.ap-southeast-1.amazonaws.com", false, true);
        a(region4, ServiceAbbreviations.t, "sts.amazonaws.com", false, true);
        Region region5 = new Region("ap-southeast-2", "amazonaws.com");
        arrayList.add(region5);
        a(region5, ServiceAbbreviations.p, "autoscaling.ap-southeast-2.amazonaws.com", false, true);
        a(region5, "cognito-identity", "cognito-identity.ap-southeast-2.amazonaws.com", false, true);
        a(region5, "cognito-idp", "cognito-idp.ap-southeast-2.amazonaws.com", false, true);
        a(region5, "cognito-sync", "cognito-sync.ap-southeast-2.amazonaws.com", false, true);
        a(region5, "data.iot", "data.iot.ap-southeast-2.amazonaws.com", false, true);
        a(region5, ServiceAbbreviations.e, "dynamodb.ap-southeast-2.amazonaws.com", false, true);
        a(region5, ServiceAbbreviations.f, "ec2.ap-southeast-2.amazonaws.com", false, true);
        a(region5, ServiceAbbreviations.v, "elasticloadbalancing.ap-southeast-2.amazonaws.com", false, true);
        a(region5, "iot", "iot.ap-southeast-2.amazonaws.com", false, true);
        a(region5, "kinesis", "kinesis.ap-southeast-2.amazonaws.com", false, true);
        a(region5, "kms", "kms.ap-southeast-2.amazonaws.com", false, true);
        a(region5, "lambda", "lambda.ap-southeast-2.amazonaws.com", false, true);
        a(region5, "logs", "logs.ap-southeast-2.amazonaws.com", false, true);
        a(region5, "polly", "polly.ap-southeast-2.amazonaws.com", false, true);
        a(region5, "s3", "s3.ap-southeast-2.amazonaws.com", false, true);
        a(region5, ServiceAbbreviations.l, "sdb.ap-southeast-2.amazonaws.com", false, true);
        a(region5, ServiceAbbreviations.m, "sns.ap-southeast-2.amazonaws.com", false, true);
        a(region5, ServiceAbbreviations.n, "sqs.ap-southeast-2.amazonaws.com", false, true);
        a(region5, ServiceAbbreviations.t, "sts.amazonaws.com", false, true);
        Region region6 = new Region("ca-central-1", "amazonaws.com");
        arrayList.add(region6);
        a(region6, ServiceAbbreviations.p, "autoscaling.ca-central-1.amazonaws.com", false, true);
        a(region6, ServiceAbbreviations.e, "dynamodb.ca-central-1.amazonaws.com", false, true);
        a(region6, ServiceAbbreviations.f, "ec2.ca-central-1.amazonaws.com", false, true);
        a(region6, ServiceAbbreviations.v, "elasticloadbalancing.ca-central-1.amazonaws.com", false, true);
        a(region6, "kinesis", "kinesis.ca-central-1.amazonaws.com", false, true);
        a(region6, "kms", "kms.ca-central-1.amazonaws.com", false, true);
        a(region6, "lambda", "lambda.ca-central-1.amazonaws.com", false, true);
        a(region6, "logs", "logs.ca-central-1.amazonaws.com", false, true);
        a(region6, "polly", "polly.ca-central-1.amazonaws.com", false, true);
        a(region6, "s3", "s3.ca-central-1.amazonaws.com", false, true);
        a(region6, ServiceAbbreviations.m, "sns.ca-central-1.amazonaws.com", false, true);
        a(region6, ServiceAbbreviations.n, "sqs.ca-central-1.amazonaws.com", false, true);
        a(region6, ServiceAbbreviations.t, "sts.amazonaws.com", false, true);
        Region region7 = new Region("eu-central-1", "amazonaws.com");
        arrayList.add(region7);
        a(region7, ServiceAbbreviations.p, "autoscaling.eu-central-1.amazonaws.com", false, true);
        a(region7, "cognito-identity", "cognito-identity.eu-central-1.amazonaws.com", false, true);
        a(region7, "cognito-idp", "cognito-idp.eu-central-1.amazonaws.com", false, true);
        a(region7, "cognito-sync", "cognito-sync.eu-central-1.amazonaws.com", false, true);
        a(region7, "data.iot", "data.iot.eu-central-1.amazonaws.com", false, true);
        a(region7, ServiceAbbreviations.e, "dynamodb.eu-central-1.amazonaws.com", false, true);
        a(region7, ServiceAbbreviations.f, "ec2.eu-central-1.amazonaws.com", false, true);
        a(region7, ServiceAbbreviations.v, "elasticloadbalancing.eu-central-1.amazonaws.com", false, true);
        a(region7, "firehose", "firehose.eu-central-1.amazonaws.com", false, true);
        a(region7, "iot", "iot.eu-central-1.amazonaws.com", false, true);
        a(region7, "kinesis", "kinesis.eu-central-1.amazonaws.com", false, true);
        a(region7, "kms", "kms.eu-central-1.amazonaws.com", false, true);
        a(region7, "lambda", "lambda.eu-central-1.amazonaws.com", false, true);
        a(region7, "logs", "logs.eu-central-1.amazonaws.com", false, true);
        a(region7, "polly", "polly.eu-central-1.amazonaws.com", false, true);
        a(region7, "s3", "s3.eu-central-1.amazonaws.com", false, true);
        a(region7, ServiceAbbreviations.m, "sns.eu-central-1.amazonaws.com", false, true);
        a(region7, ServiceAbbreviations.n, "sqs.eu-central-1.amazonaws.com", false, true);
        a(region7, ServiceAbbreviations.t, "sts.amazonaws.com", false, true);
        Region region8 = new Region("eu-west-1", "amazonaws.com");
        arrayList.add(region8);
        a(region8, ServiceAbbreviations.p, "autoscaling.eu-west-1.amazonaws.com", false, true);
        a(region8, "cognito-identity", "cognito-identity.eu-west-1.amazonaws.com", false, true);
        a(region8, "cognito-idp", "cognito-idp.eu-west-1.amazonaws.com", false, true);
        a(region8, "cognito-sync", "cognito-sync.eu-west-1.amazonaws.com", false, true);
        a(region8, "data.iot", "data.iot.eu-west-1.amazonaws.com", false, true);
        a(region8, ServiceAbbreviations.e, "dynamodb.eu-west-1.amazonaws.com", false, true);
        a(region8, ServiceAbbreviations.f, "ec2.eu-west-1.amazonaws.com", false, true);
        a(region8, ServiceAbbreviations.v, "elasticloadbalancing.eu-west-1.amazonaws.com", false, true);
        a(region8, "email", "email.eu-west-1.amazonaws.com", false, true);
        a(region8, "firehose", "firehose.eu-west-1.amazonaws.com", false, true);
        a(region8, "iot", "iot.eu-west-1.amazonaws.com", false, true);
        a(region8, "kinesis", "kinesis.eu-west-1.amazonaws.com", false, true);
        a(region8, "kms", "kms.eu-west-1.amazonaws.com", false, true);
        a(region8, "lambda", "lambda.eu-west-1.amazonaws.com", false, true);
        a(region8, "logs", "logs.eu-west-1.amazonaws.com", false, true);
        a(region8, "machinelearning", "machinelearning.eu-west-1.amazonaws.com", false, true);
        a(region8, "polly", "polly.eu-west-1.amazonaws.com", false, true);
        a(region8, "rekognition", "rekognition.eu-west-1.amazonaws.com", false, true);
        a(region8, "s3", "s3.eu-west-1.amazonaws.com", false, true);
        a(region8, ServiceAbbreviations.l, "sdb.eu-west-1.amazonaws.com", false, true);
        a(region8, ServiceAbbreviations.m, "sns.eu-west-1.amazonaws.com", false, true);
        a(region8, ServiceAbbreviations.n, "sqs.eu-west-1.amazonaws.com", false, true);
        a(region8, ServiceAbbreviations.t, "sts.amazonaws.com", false, true);
        Region region9 = new Region("eu-west-2", "amazonaws.com");
        arrayList.add(region9);
        a(region9, ServiceAbbreviations.p, "autoscaling.eu-west-2.amazonaws.com", false, true);
        a(region9, "cognito-identity", "cognito-identity.eu-west-2.amazonaws.com", false, true);
        a(region9, "cognito-idp", "cognito-idp.eu-west-2.amazonaws.com", false, true);
        a(region9, "cognito-sync", "cognito-sync.eu-west-2.amazonaws.com", false, true);
        a(region9, ServiceAbbreviations.e, "dynamodb.eu-west-2.amazonaws.com", false, true);
        a(region9, ServiceAbbreviations.f, "ec2.eu-west-2.amazonaws.com", false, true);
        a(region9, ServiceAbbreviations.v, "elasticloadbalancing.eu-west-2.amazonaws.com", false, true);
        a(region9, "iot", "iot.eu-west-2.amazonaws.com", false, true);
        a(region9, "kinesis", "kinesis.eu-west-2.amazonaws.com", false, true);
        a(region9, "kms", "kms.eu-west-2.amazonaws.com", false, true);
        a(region9, "lambda", "lambda.eu-west-2.amazonaws.com", false, true);
        a(region9, "logs", "logs.eu-west-2.amazonaws.com", false, true);
        a(region9, "polly", "polly.eu-west-2.amazonaws.com", false, true);
        a(region9, "s3", "s3.eu-west-2.amazonaws.com", false, true);
        a(region9, ServiceAbbreviations.m, "sns.eu-west-2.amazonaws.com", false, true);
        a(region9, ServiceAbbreviations.n, "sqs.eu-west-2.amazonaws.com", false, true);
        a(region9, ServiceAbbreviations.t, "sts.amazonaws.com", false, true);
        Region region10 = new Region("eu-west-3", "amazonaws.com");
        arrayList.add(region10);
        a(region10, ServiceAbbreviations.p, "autoscaling.eu-west-3.amazonaws.com", false, true);
        a(region10, ServiceAbbreviations.e, "dynamodb.eu-west-3.amazonaws.com", false, true);
        a(region10, ServiceAbbreviations.f, "ec2.eu-west-3.amazonaws.com", false, true);
        a(region10, ServiceAbbreviations.v, "elasticloadbalancing.eu-west-3.amazonaws.com", false, true);
        a(region10, "kinesis", "kinesis.eu-west-3.amazonaws.com", false, true);
        a(region10, "kms", "kms.eu-west-3.amazonaws.com", false, true);
        a(region10, "lambda", "lambda.eu-west-3.amazonaws.com", false, true);
        a(region10, "logs", "logs.eu-west-3.amazonaws.com", false, true);
        a(region10, "polly", "polly.eu-west-3.amazonaws.com", false, true);
        a(region10, "s3", "s3.eu-west-3.amazonaws.com", false, true);
        a(region10, ServiceAbbreviations.m, "sns.eu-west-3.amazonaws.com", false, true);
        a(region10, ServiceAbbreviations.n, "sqs.eu-west-3.amazonaws.com", false, true);
        a(region10, ServiceAbbreviations.t, "sts.amazonaws.com", false, true);
        Region region11 = new Region("sa-east-1", "amazonaws.com");
        arrayList.add(region11);
        a(region11, ServiceAbbreviations.p, "autoscaling.sa-east-1.amazonaws.com", false, true);
        a(region11, ServiceAbbreviations.e, "dynamodb.sa-east-1.amazonaws.com", false, true);
        a(region11, ServiceAbbreviations.f, "ec2.sa-east-1.amazonaws.com", false, true);
        a(region11, ServiceAbbreviations.v, "elasticloadbalancing.sa-east-1.amazonaws.com", false, true);
        a(region11, "kinesis", "kinesis.sa-east-1.amazonaws.com", false, true);
        a(region11, "kms", "kms.sa-east-1.amazonaws.com", false, true);
        a(region11, "lambda", "lambda.sa-east-1.amazonaws.com", false, true);
        a(region11, "logs", "logs.sa-east-1.amazonaws.com", false, true);
        a(region11, "polly", "polly.sa-east-1.amazonaws.com", false, true);
        a(region11, "s3", "s3.sa-east-1.amazonaws.com", false, true);
        a(region11, ServiceAbbreviations.l, "sdb.sa-east-1.amazonaws.com", false, true);
        a(region11, ServiceAbbreviations.m, "sns.sa-east-1.amazonaws.com", false, true);
        a(region11, ServiceAbbreviations.n, "sqs.sa-east-1.amazonaws.com", false, true);
        a(region11, ServiceAbbreviations.t, "sts.amazonaws.com", false, true);
        Region region12 = new Region("us-east-1", "amazonaws.com");
        arrayList.add(region12);
        a(region12, ServiceAbbreviations.p, "autoscaling.us-east-1.amazonaws.com", false, true);
        a(region12, "cognito-identity", "cognito-identity.us-east-1.amazonaws.com", false, true);
        a(region12, "cognito-idp", "cognito-idp.us-east-1.amazonaws.com", false, true);
        a(region12, "cognito-sync", "cognito-sync.us-east-1.amazonaws.com", false, true);
        a(region12, "data.iot", "data.iot.us-east-1.amazonaws.com", false, true);
        a(region12, ServiceAbbreviations.e, "dynamodb.us-east-1.amazonaws.com", false, true);
        a(region12, ServiceAbbreviations.f, "ec2.us-east-1.amazonaws.com", false, true);
        a(region12, ServiceAbbreviations.v, "elasticloadbalancing.us-east-1.amazonaws.com", false, true);
        a(region12, "email", "email.us-east-1.amazonaws.com", false, true);
        a(region12, "firehose", "firehose.us-east-1.amazonaws.com", false, true);
        a(region12, "iot", "iot.us-east-1.amazonaws.com", false, true);
        a(region12, "kinesis", "kinesis.us-east-1.amazonaws.com", false, true);
        a(region12, "kms", "kms.us-east-1.amazonaws.com", false, true);
        a(region12, "lambda", "lambda.us-east-1.amazonaws.com", false, true);
        a(region12, "logs", "logs.us-east-1.amazonaws.com", false, true);
        a(region12, "machinelearning", "machinelearning.us-east-1.amazonaws.com", false, true);
        a(region12, "mobileanalytics", "mobileanalytics.us-east-1.amazonaws.com", false, true);
        a(region12, "pinpoint", "pinpoint.us-east-1.amazonaws.com", false, true);
        a(region12, "polly", "polly.us-east-1.amazonaws.com", false, true);
        a(region12, "rekognition", "rekognition.us-east-1.amazonaws.com", false, true);
        a(region12, "s3", Constants.b, false, true);
        a(region12, ServiceAbbreviations.l, "sdb.amazonaws.com", false, true);
        a(region12, ServiceAbbreviations.m, "sns.us-east-1.amazonaws.com", false, true);
        a(region12, ServiceAbbreviations.n, "sqs.us-east-1.amazonaws.com", false, true);
        a(region12, ServiceAbbreviations.t, "sts.amazonaws.com", false, true);
        Region region13 = new Region("us-east-2", "amazonaws.com");
        arrayList.add(region13);
        a(region13, ServiceAbbreviations.p, "autoscaling.us-east-2.amazonaws.com", false, true);
        a(region13, "cognito-identity", "cognito-identity.us-east-2.amazonaws.com", false, true);
        a(region13, "cognito-idp", "cognito-idp.us-east-2.amazonaws.com", false, true);
        a(region13, "cognito-sync", "cognito-sync.us-east-2.amazonaws.com", false, true);
        a(region13, ServiceAbbreviations.e, "dynamodb.us-east-2.amazonaws.com", false, true);
        a(region13, ServiceAbbreviations.f, "ec2.us-east-2.amazonaws.com", false, true);
        a(region13, ServiceAbbreviations.v, "elasticloadbalancing.us-east-2.amazonaws.com", false, true);
        a(region13, "firehose", "firehose.us-east-2.amazonaws.com", false, true);
        a(region13, "iot", "iot.us-east-2.amazonaws.com", false, true);
        a(region13, "kinesis", "kinesis.us-east-2.amazonaws.com", false, true);
        a(region13, "kms", "kms.us-east-2.amazonaws.com", false, true);
        a(region13, "lambda", "lambda.us-east-2.amazonaws.com", false, true);
        a(region13, "logs", "logs.us-east-2.amazonaws.com", false, true);
        a(region13, "polly", "polly.us-east-2.amazonaws.com", false, true);
        a(region13, "s3", "s3.us-east-2.amazonaws.com", false, true);
        a(region13, ServiceAbbreviations.m, "sns.us-east-2.amazonaws.com", false, true);
        a(region13, ServiceAbbreviations.n, "sqs.us-east-2.amazonaws.com", false, true);
        a(region13, ServiceAbbreviations.t, "sts.amazonaws.com", false, true);
        Region region14 = new Region("us-west-1", "amazonaws.com");
        arrayList.add(region14);
        a(region14, ServiceAbbreviations.p, "autoscaling.us-west-1.amazonaws.com", false, true);
        a(region14, ServiceAbbreviations.e, "dynamodb.us-west-1.amazonaws.com", false, true);
        a(region14, ServiceAbbreviations.f, "ec2.us-west-1.amazonaws.com", false, true);
        a(region14, ServiceAbbreviations.v, "elasticloadbalancing.us-west-1.amazonaws.com", false, true);
        a(region14, "kinesis", "kinesis.us-west-1.amazonaws.com", false, true);
        a(region14, "kms", "kms.us-west-1.amazonaws.com", false, true);
        a(region14, "lambda", "lambda.us-west-1.amazonaws.com", false, true);
        a(region14, "logs", "logs.us-west-1.amazonaws.com", false, true);
        a(region14, "polly", "polly.us-west-1.amazonaws.com", false, true);
        a(region14, "s3", "s3.us-west-1.amazonaws.com", false, true);
        a(region14, ServiceAbbreviations.l, "sdb.us-west-1.amazonaws.com", false, true);
        a(region14, ServiceAbbreviations.m, "sns.us-west-1.amazonaws.com", false, true);
        a(region14, ServiceAbbreviations.n, "sqs.us-west-1.amazonaws.com", false, true);
        a(region14, ServiceAbbreviations.t, "sts.amazonaws.com", false, true);
        Region region15 = new Region("us-west-2", "amazonaws.com");
        arrayList.add(region15);
        a(region15, ServiceAbbreviations.p, "autoscaling.us-west-2.amazonaws.com", false, true);
        a(region15, "cognito-identity", "cognito-identity.us-west-2.amazonaws.com", false, true);
        a(region15, "cognito-idp", "cognito-idp.us-west-2.amazonaws.com", false, true);
        a(region15, "cognito-sync", "cognito-sync.us-west-2.amazonaws.com", false, true);
        a(region15, "data.iot", "data.iot.us-west-2.amazonaws.com", false, true);
        a(region15, ServiceAbbreviations.e, "dynamodb.us-west-2.amazonaws.com", false, true);
        a(region15, ServiceAbbreviations.f, "ec2.us-west-2.amazonaws.com", false, true);
        a(region15, ServiceAbbreviations.v, "elasticloadbalancing.us-west-2.amazonaws.com", false, true);
        a(region15, "email", "email.us-west-2.amazonaws.com", false, true);
        a(region15, "firehose", "firehose.us-west-2.amazonaws.com", false, true);
        a(region15, "iot", "iot.us-west-2.amazonaws.com", false, true);
        a(region15, "kinesis", "kinesis.us-west-2.amazonaws.com", false, true);
        a(region15, "kms", "kms.us-west-2.amazonaws.com", false, true);
        a(region15, "lambda", "lambda.us-west-2.amazonaws.com", false, true);
        a(region15, "logs", "logs.us-west-2.amazonaws.com", false, true);
        a(region15, "polly", "polly.us-west-2.amazonaws.com", false, true);
        a(region15, "rekognition", "rekognition.us-west-2.amazonaws.com", false, true);
        a(region15, "s3", "s3.us-west-2.amazonaws.com", false, true);
        a(region15, ServiceAbbreviations.l, "sdb.us-west-2.amazonaws.com", false, true);
        a(region15, ServiceAbbreviations.m, "sns.us-west-2.amazonaws.com", false, true);
        a(region15, ServiceAbbreviations.n, "sqs.us-west-2.amazonaws.com", false, true);
        a(region15, ServiceAbbreviations.t, "sts.amazonaws.com", false, true);
        Region region16 = new Region("cn-north-1", "amazonaws.com.cn");
        arrayList.add(region16);
        a(region16, ServiceAbbreviations.p, "autoscaling.cn-north-1.amazonaws.com.cn", false, true);
        a(region16, "cognito-identity", "cognito-identity.cn-north-1.amazonaws.com.cn", false, true);
        a(region16, ServiceAbbreviations.e, "dynamodb.cn-north-1.amazonaws.com.cn", false, true);
        a(region16, ServiceAbbreviations.f, "ec2.cn-north-1.amazonaws.com.cn", false, true);
        a(region16, ServiceAbbreviations.v, "elasticloadbalancing.cn-north-1.amazonaws.com.cn", false, true);
        a(region16, "iot", "iot.cn-north-1.amazonaws.com.cn", false, true);
        a(region16, "kinesis", "kinesis.cn-north-1.amazonaws.com.cn", false, true);
        a(region16, "lambda", "lambda.cn-north-1.amazonaws.com.cn", false, true);
        a(region16, "logs", "logs.cn-north-1.amazonaws.com.cn", false, true);
        a(region16, "s3", "s3.cn-north-1.amazonaws.com.cn", false, true);
        a(region16, ServiceAbbreviations.m, "sns.cn-north-1.amazonaws.com.cn", false, true);
        a(region16, ServiceAbbreviations.n, "sqs.cn-north-1.amazonaws.com.cn", false, true);
        a(region16, ServiceAbbreviations.t, "sts.cn-north-1.amazonaws.com.cn", false, true);
        Region region17 = new Region("cn-northwest-1", "amazonaws.com.cn");
        arrayList.add(region17);
        a(region17, ServiceAbbreviations.p, "autoscaling.cn-northwest-1.amazonaws.com.cn", false, true);
        a(region17, ServiceAbbreviations.e, "dynamodb.cn-northwest-1.amazonaws.com.cn", false, true);
        a(region17, ServiceAbbreviations.f, "ec2.cn-northwest-1.amazonaws.com.cn", false, true);
        a(region17, ServiceAbbreviations.v, "elasticloadbalancing.cn-northwest-1.amazonaws.com.cn", false, true);
        a(region17, "kinesis", "kinesis.cn-northwest-1.amazonaws.com.cn", false, true);
        a(region17, "logs", "logs.cn-northwest-1.amazonaws.com.cn", false, true);
        a(region17, "s3", "s3.cn-northwest-1.amazonaws.com.cn", false, true);
        a(region17, ServiceAbbreviations.m, "sns.cn-northwest-1.amazonaws.com.cn", false, true);
        a(region17, ServiceAbbreviations.n, "sqs.cn-northwest-1.amazonaws.com.cn", false, true);
        a(region17, ServiceAbbreviations.t, "sts.amazonaws.com.cn", false, true);
        Region region18 = new Region("us-gov-west-1", "amazonaws.com");
        arrayList.add(region18);
        a(region18, ServiceAbbreviations.p, "autoscaling.us-gov-west-1.amazonaws.com", false, true);
        a(region18, ServiceAbbreviations.e, "dynamodb.us-gov-west-1.amazonaws.com", false, true);
        a(region18, ServiceAbbreviations.f, "ec2.us-gov-west-1.amazonaws.com", false, true);
        a(region18, ServiceAbbreviations.v, "elasticloadbalancing.us-gov-west-1.amazonaws.com", false, true);
        a(region18, "kinesis", "kinesis.us-gov-west-1.amazonaws.com", false, true);
        a(region18, "kms", "kms.us-gov-west-1.amazonaws.com", false, true);
        a(region18, "lambda", "lambda.us-gov-west-1.amazonaws.com", false, true);
        a(region18, "logs", "logs.us-gov-west-1.amazonaws.com", false, true);
        a(region18, "rekognition", "rekognition.us-gov-west-1.amazonaws.com", false, true);
        a(region18, "s3", "s3.us-gov-west-1.amazonaws.com", false, true);
        a(region18, ServiceAbbreviations.m, "sns.us-gov-west-1.amazonaws.com", false, true);
        a(region18, ServiceAbbreviations.n, "sqs.us-gov-west-1.amazonaws.com", false, true);
        a(region18, ServiceAbbreviations.t, "sts.amazonaws.com", false, true);
        Region region19 = new Region("eu-north-1", "amazonaws.com");
        arrayList.add(region19);
        a(region19, ServiceAbbreviations.p, "autoscaling.eu-north-1.amazonaws.com", false, true);
        a(region19, ServiceAbbreviations.e, "dynamodb.eu-north-1.amazonaws.com", false, true);
        a(region19, ServiceAbbreviations.f, "ec2.eu-north-1.amazonaws.com", false, true);
        a(region19, ServiceAbbreviations.v, "elasticloadbalancing.eu-north-1.amazonaws.com", false, true);
        a(region19, "firehose", "firehose.eu-north-1.amazonaws.com", false, true);
        a(region19, "iot", "iot.eu-north-1.amazonaws.com", false, true);
        a(region19, "kinesis", "kinesis.eu-north-1.amazonaws.com", false, true);
        a(region19, "kms", "kms.eu-north-1.amazonaws.com", false, true);
        a(region19, "lambda", "lambda.eu-north-1.amazonaws.com", false, true);
        a(region19, "logs", "logs.eu-north-1.amazonaws.com", false, true);
        a(region19, "s3", "s3.eu-north-1.amazonaws.com", false, true);
        a(region19, ServiceAbbreviations.m, "sns.eu-north-1.amazonaws.com", false, true);
        a(region19, ServiceAbbreviations.n, "sqs.eu-north-1.amazonaws.com", false, true);
        a(region19, ServiceAbbreviations.t, "sts.amazonaws.com", false, true);
        return arrayList;
    }

    private static void a(Region region, String str, String str2, boolean z, boolean z2) {
        Map<String, String> mapC = region.c();
        Map<String, Boolean> mapD = region.d();
        Map<String, Boolean> mapE = region.e();
        mapC.put(str, str2);
        mapD.put(str, Boolean.valueOf(z));
        mapE.put(str, Boolean.valueOf(z2));
    }
}
